/**
 * Tool: get_billing_rules —— 查扣费规则(免费,本地,无后端调用)。
 *
 * 返回采集类工具的计费公式、各因子含义、典型示例、AI 分析的计费、免费边界。
 * 一次调用拿到完整计费口径,不用从各工具 description 里拼。
 *
 * 计费公式(与 DataScaler 后端一致):
 *   credits = 品牌数 × 加权渠道单位 × 关键词数 × 页数 × 0.02
 *   Pangolinfo 积分 = credits × 600 = 品牌数 × 加权渠道单位 × 关键词数 × 页数 × 12
 *   普通社媒渠道=1,Threads=1,Reddit=2,amazon_reviews 不参与采集公式。
 */

import { z } from "zod";

import type { Tool } from "./_types.js";
import { t } from "../i18n.js";

const inputSchema = z.object({});

export const getBillingRules: Tool<typeof inputSchema> = {
  name: "get_billing_rules",
  description: t({
    zh: `[扣费规则 · 免费 · 0 调用] 查采集类工具的计费公式与口径。纯本地数据,不打后端、不扣费。
AI 被问"怎么扣费/多少钱/计费规则"时调这个,不用从各工具 description 里拼。
Returns: { formula, unitPrice, factors, examples, analyzeBrand, free }。`,
    en: `[Billing rules · FREE · 0 backend calls] Return the collection billing formula and its factors. Local only, no backend call, no charge.
Call this when asked "how am I charged / how much / billing rules" — instead of piecing it together from tool descriptions.
Returns: { formula, unitPrice, factors, examples, analyzeBrand, free }.`,
  }),
  inputSchema,
  async execute(_input, ctx) {
    ctx.logger.info("get_billing_rules");
    return {
      formula: t({
        zh: "品牌数 × 加权渠道单位 × 关键词数 × 页数 × 12(积分)",
        en: "brandCount × weightedChannelUnits × keywordCount × pages × 12 (points)",
      }),
      unitPrice: t({
        zh: "12 积分 / 品牌 / 渠道单位 / 关键词 / 页;普通渠道=1,Threads=1,Reddit=2",
        en: "12 points / brand / channel unit / keyword / page; normal channels=1, Threads=1, Reddit=2",
      }),
      factors: {
        brandCount: t({
          zh: "知识空间(create_space)=1;完整品牌(setup_brand/refresh_brand)=1+竞品数(竞品最多 3)",
          en: "Knowledge space (create_space)=1; full brand (setup_brand/refresh_brand)=1+competitors (max 3)",
        }),
        weightedChannelUnits: t({
          zh: "默认 7 社媒各按 1 个渠道单位计(tiktok/instagram/youtube/x/facebook/pinterest/trustpilot);可选 threads=1、reddit=2;amazon_reviews 不参与采集公式",
          en: "Default 7 social platforms each count as 1 channel unit (tiktok/instagram/youtube/x/facebook/pinterest/trustpilot); optional threads=1, reddit=2; amazon_reviews is excluded from collection billing",
        }),
        keywordCount: t({
          zh: "默认生成约 12 个英文关键词(随品牌浮动,上限 30);用户可自定义 1-30 个。计费按实际关键词数",
          en: "~12 English keywords auto-generated by default (varies by brand, max 30); user can override 1-30. Billed by actual keyword count",
        }),
        pages: t({
          zh: "用户指定 1-10 页(默认 10)。页数越多数据越全、耗时越长、费用越高",
          en: "User-specified 1-10 pages (default 10). More pages = more data, longer, costlier",
        }),
      },
      examples: [
        t({
          zh: "知识空间、4 个普通渠道单位、12 关键词、3 页:1×4×12×3×12 = 1728 积分",
          en: "Knowledge space, 4 normal channel units, 12 keywords, 3 pages: 1×4×12×3×12 = 1728 points",
        }),
        t({
          zh: "知识空间、默认 7 渠道单位、12 关键词、10 页:1×7×12×10×12 = 10080 积分",
          en: "Knowledge space, default 7 channel units, 12 keywords, 10 pages: 1×7×12×10×12 = 10080 points",
        }),
        t({
          zh: "知识空间、默认 7 社媒 + Reddit、12 关键词、10 页:1×(7+2)×12×10×12 = 12960 积分",
          en: "Knowledge space, default 7 social + Reddit, 12 keywords, 10 pages: 1×(7+2)×12×10×12 = 12960 points",
        }),
        t({
          zh: "标准 VOC 报告(完整品牌 1+3竞品=4 品牌)×7 渠道单位×12 关键词×10 页:4×7×12×10×12 = 40320 积分",
          en: "Standard VOC report (full brand 1+3 competitors=4) × 7 channel units × 12 keywords × 10 pages: 4×7×12×10×12 = 40320 points",
        }),
      ],
      analyzeBrand: t({
        zh: "analyze_brand(AI 深度分析):600 积分/次,成功才扣",
        en: "analyze_brand (AI deep analysis): 600 points/call, charged only on success",
      }),
      billingMode: t({
        zh: "两种计费模式并存,当前用户是哪种见 get_context 返回的 result.data.billingMode。prepaid:扣 Pangolinfo 积点(充值积点即用,余额不足报额度不足);postpaid:不扣也不展示积分余额,按账期用量月底结算(有账期用量上限,超上限报额度不足)。两种模式的采集/分析单价相同(本工具公式),仅结算方式不同。",
        en: "Two billing modes coexist; which one applies to the current user — see result.data.billingMode from get_context. prepaid: deducts Pangolinfo points (top up points to use; insufficient balance → quota error). postpaid: no point balance is deducted or displayed; usage is settled monthly by billing-period usage (with a period usage cap; over cap → quota error). Per-call unit prices are identical for both (see this tool's formula); only the settlement method differs.",
      }),
      free: t({
        zh: "所有只读工具(metrics/posts/sentiment/voice-share/risk-alerts/...)、prepare_space、diagnose_brand、get_refresh_progress、wait_for_refresh、get_brand_summary、get_context、explain_error、get_billing_rules 全免费。",
        en: "All read tools (metrics/posts/sentiment/voice-share/risk-alerts/...), prepare_space, diagnose_brand, get_refresh_progress, wait_for_refresh, get_brand_summary, get_context, explain_error, get_billing_rules are free.",
      }),
    };
  },
};
